services:
  db:
    image: postgres
    volumes:
      - /home/mateus/workflow/study_project/data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - mateus_study

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
    - mateus_study

networks:
  mateus_study:
    driver: bridge